use uci

diff --git a/files/shadowvpn.init b/files/shadowvpn.init
--- a/files/shadowvpn.init
+++ b/files/shadowvpn.init
@@ -3,9 +3,9 @@
 
 START=90
 STOP=15
-EXTRA_COMMANDS="restart"
 
-CONFIG=/etc/shadowvpn/client.conf
+CONFIG=/var/etc/shadowvpn.conf
+TPL=/etc/shadowvpn/client.conf
 
 boot() {
 	if [ ! -f "/dev/net/tun" ]; then
@@ -15,14 +15,34 @@ boot() {
 	fi
 }
 
+start_vpn() {
+	local enable server port password mtu intf
+	config_get_bool enable $1 enable
+	[ "$enable" = 1 ] || return 0
+	config_get server $1 server
+	config_get port $1 port
+	config_get password $1 password
+	config_get mtu $1 mtu
+	config_get intf $1 intf
+	if [ -z "$server" -o -z "$port" -o -z "$password" ]; then
+		echo "Missing required configuration"
+		return 2
+	fi
+	mkdir -p /var/etc
+	cat $TPL | grep -v "^#" | grep -v "^$" | \
+	sed -e "s#|SERVER|#$server#g" \
+		-e "s#|PORT|#$port#g" \
+		-e "s#|PASSWORD|#$password#g" \
+		-e "s#|MTU|#$mtu#g" \
+		-e "s#|INTF|#$intf#g" >$CONFIG
+	/usr/bin/shadowvpn -c $CONFIG -s start
+}
+
 start() {
-	shadowvpn -c $CONFIG -s start
+	config_load shadowvpn
+	config_foreach start_vpn shadowvpn
 }
 
 stop() {
-	shadowvpn -c $CONFIG -s stop
-}
-
-restart() {
-	shadowvpn -c $CONFIG -s restart
+	/usr/bin/shadowvpn -c $CONFIG -s stop
 }
